#!/usr/bin/env bun

/**
 * LibreCode CLI Build Script
 *
 * Compiles the CLI into platform-specific binaries using Bun's compile target.
 *
 * Stages:
 *   1. Fetch models snapshot (or use cached/local version)
 *   2. Load SQL migrations
 *   3. Install platform-specific native deps (unless --skip-install)
 *   4. Compile binaries for each target
 *
 * Flags:
 *   --single         Build only for current platform + architecture
 *   --baseline       When --single, also build x64 avx2=false variant
 *   --skip-install   Skip bun install of platform-specific native modules
 *   --target <name>  Build only the specified target (e.g. "linux-x64", "darwin-arm64-musl")
 *                    Can be specified multiple times for multiple targets
 *   --skip-models    Skip models snapshot fetch (use existing file)
 *
 * Environment variables:
 *   LIBRECODE_MODELS_URL      Override models API URL (default: https://models.dev)
 *   MODELS_DEV_API_JSON       Path to local models JSON file (skips network fetch)
 *   LIBRECODE_VERSION         Override version string
 *   LIBRECODE_CHANNEL         Override release channel
 */

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"
import solidPlugin from "@opentui/solid/bun-plugin"
import { loadMigrations } from "./load-migrations"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import { Script } from "@librecode/script"
import pkg from "../package.json"

// ── Flag parsing ──────────────────────────────────────────────

const args = process.argv.slice(2)

const singleFlag = args.includes("--single")
const baselineFlag = args.includes("--baseline")
const skipInstall = args.includes("--skip-install")
const skipModels = args.includes("--skip-models")

// Parse --target flags (can appear multiple times)
const targetFilters: string[] = []
for (let i = 0; i < args.length; i++) {
  if (args[i] === "--target" && args[i + 1]) {
    targetFilters.push(args[i + 1])
    i++
  }
}

// ── Helpers ───────────────────────────────────────────────────

async function fetchModelsWithRetry(url: string, attempts = 5): Promise<string> {
  let lastError: unknown
  for (let attempt = 1; attempt <= attempts; attempt++) {
    console.log(`Fetching models from ${url} (attempt ${attempt}/${attempts})`)
    try {
      const controller = new AbortController()
      const timer = setTimeout(() => controller.abort(), 30_000)
      try {
        const response = await fetch(url, { signal: controller.signal })
        if (!response.ok) {
          throw new Error(`HTTP ${response.status} ${response.statusText}`)
        }
        return await response.text()
      } finally {
        clearTimeout(timer)
      }
    } catch (err) {
      lastError = err
      const msg = err instanceof Error ? err.message : String(err)
      console.error(`  attempt ${attempt} failed: ${msg}`)
      if (attempt < attempts) {
        const backoffMs = Math.min(2_000 * 2 ** (attempt - 1), 30_000)
        console.error(`  retrying in ${backoffMs}ms…`)
        await new Promise((resolve) => setTimeout(resolve, backoffMs))
      }
    }
  }
  console.error(`Failed to fetch models after ${attempts} attempts: ${String(lastError)}`)
  process.exit(1)
}

// ── Stage 1: Models snapshot ──────────────────────────────────

const snapshotPath = path.join(dir, "src/provider/models-snapshot.ts")

if (skipModels && fs.existsSync(snapshotPath)) {
  console.log("Skipping models fetch (--skip-models, using existing snapshot)")
} else {
  const modelsUrl = process.env.LIBRECODE_MODELS_URL || "https://models.dev"
  let modelsData: string

  if (process.env.MODELS_DEV_API_JSON) {
    console.log(`Reading models from ${process.env.MODELS_DEV_API_JSON}`)
    modelsData = await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  } else {
    modelsData = await fetchModelsWithRetry(`${modelsUrl}/api.json`)
  }

  await Bun.write(
    snapshotPath,
    `// Auto-generated by build.ts — do not edit\nexport const snapshot = ${modelsData} as const\n`,
  )
  console.log("Generated models-snapshot.ts")
}

// ── Stage 2: Load migrations ──────────────────────────────────

const migrations = await loadMigrations(dir)
console.log(`Loaded ${migrations.length} migrations`)

// ── Stage 3: Define and filter targets ────────────────────────

interface BuildTarget {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}

const allTargets: BuildTarget[] = [
  // Linux glibc
  { os: "linux", arch: "arm64" },
  { os: "linux", arch: "x64" },
  { os: "linux", arch: "x64", avx2: false },
  // Linux musl
  { os: "linux", arch: "arm64", abi: "musl" },
  { os: "linux", arch: "x64", abi: "musl" },
  { os: "linux", arch: "x64", abi: "musl", avx2: false },
  // macOS
  { os: "darwin", arch: "arm64" },
  { os: "darwin", arch: "x64" },
  { os: "darwin", arch: "x64", avx2: false },
  // Windows
  { os: "win32", arch: "arm64" },
  { os: "win32", arch: "x64" },
  { os: "win32", arch: "x64", avx2: false },
]

function targetName(item: BuildTarget): string {
  return [
    pkg.name,
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi,
  ]
    .filter(Boolean)
    .join("-")
}

/** Short name for --target matching (e.g. "linux-x64", "darwin-arm64-musl") */
function targetShortName(item: BuildTarget): string {
  return [item.os === "win32" ? "windows" : item.os, item.arch, item.avx2 === false ? "baseline" : undefined, item.abi]
    .filter(Boolean)
    .join("-")
}

let targets: BuildTarget[]

if (targetFilters.length > 0) {
  // --target flag: match by short name
  targets = allTargets.filter((item) => targetFilters.includes(targetShortName(item)))
  if (targets.length === 0) {
    console.error(`No targets matched: ${targetFilters.join(", ")}`)
    console.error(`Available targets: ${allTargets.map(targetShortName).join(", ")}`)
    process.exit(1)
  }
} else if (singleFlag) {
  targets = allTargets.filter((item) => {
    if (item.os !== process.platform || item.arch !== process.arch) return false
    if (item.avx2 === false) return baselineFlag
    if (item.abi !== undefined) return false
    return true
  })
} else {
  targets = allTargets
}

console.log(`Building ${targets.length} target(s): ${targets.map(targetShortName).join(", ")}`)

// ── Stage 4: Clean + install deps ─────────────────────────────

await $`rm -rf dist`

if (!skipInstall) {
  console.log("Installing platform-specific native modules...")
  await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}

// ── Stage 5: Compile each target ──────────────────────────────

const binaries: Record<string, string> = {}

for (const item of targets) {
  const name = targetName(item)
  const short = targetShortName(item)
  console.log(`\n── Building ${name} ──`)

  await $`mkdir -p dist/${name}/bin`

  // Resolve parser worker
  const localPath = path.resolve(dir, "node_modules/@opentui/core/parser.worker.js")
  const rootPath = path.resolve(dir, "../../node_modules/@opentui/core/parser.worker.js")
  const parserWorker = fs.realpathSync(fs.existsSync(localPath) ? localPath : rootPath)
  const workerPath = "./src/cli/cmd/tui/worker.ts"

  // Platform-specific bunfs root
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

  const binaryName = item.os === "win32" ? "librecode.exe" : "librecode"

  const result = await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [solidPlugin],
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace(pkg.name, "bun") as any,
      outfile: `dist/${name}/bin/${binaryName}`,
      execArgv: [`--user-agent=librecode/${Script.version}`, "--use-system-ca", "--"],
      windows: {},
    },
    entrypoints: ["./src/index.ts", parserWorker, workerPath],
    define: {
      LIBRECODE_VERSION: `'${Script.version}'`,
      LIBRECODE_MIGRATIONS: JSON.stringify(migrations),
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      LIBRECODE_WORKER_PATH: workerPath,
      LIBRECODE_CHANNEL: `'${Script.channel}'`,
      LIBRECODE_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
    },
  })

  if (!result.success) {
    console.error(`\nBuild failed for ${name}:`)
    for (const log of result.logs) {
      console.error(`  ${log}`)
    }
    process.exit(1)
  }

  // Clean up worker directory artifact
  await $`rm -rf ./dist/${name}/bin/tui`

  // Write platform-specific package.json
  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )

  binaries[name] = Script.version
  console.log(`Built ${name} → dist/${name}/bin/${binaryName}`)
}

// ── Summary ───────────────────────────────────────────────────

console.log(`\nBuild complete: ${Object.keys(binaries).length} binaries`)
for (const [name, version] of Object.entries(binaries)) {
  console.log(`  ${name} @ ${version}`)
}

export { binaries }
