#!/usr/bin/env bun

/**
 * Fetches the models.dev API snapshot and writes it to src/provider/models-snapshot.ts.
 *
 * Environment variables:
 *   LIBRECODE_MODELS_URL   - Override the models API base URL (default: https://models.dev)
 *   MODELS_DEV_API_JSON    - Path to a local JSON file to use instead of fetching
 *
 * Usage:
 *   bun run script/fetch-models.ts
 *   MODELS_DEV_API_JSON=/path/to/api.json bun run script/fetch-models.ts
 */

import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

const modelsUrl = process.env.LIBRECODE_MODELS_URL || "https://models.dev"
const outFile = path.join(dir, "src/provider/models-snapshot.ts")

let modelsData: string

if (process.env.MODELS_DEV_API_JSON) {
  console.log(`Reading models from ${process.env.MODELS_DEV_API_JSON}`)
  modelsData = await Bun.file(process.env.MODELS_DEV_API_JSON).text()
} else {
  console.log(`Fetching models from ${modelsUrl}/api.json`)
  const response = await fetch(`${modelsUrl}/api.json`)
  if (!response.ok) {
    console.error(`Failed to fetch models: ${response.status} ${response.statusText}`)
    process.exit(1)
  }
  modelsData = await response.text()
}

// Validate it's actually JSON
try {
  JSON.parse(modelsData)
} catch {
  console.error("Models data is not valid JSON")
  process.exit(1)
}

await Bun.write(outFile, `// Auto-generated by fetch-models.ts — do not edit\nexport const snapshot = ${modelsData} as const\n`)
console.log(`Wrote models snapshot to ${path.relative(dir, outFile)}`)
