function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

const _experimental = truthy("LIBRECODE_EXPERIMENTAL")
const _disableClaudeCode = truthy("LIBRECODE_DISABLE_CLAUDE_CODE")
const _disableClaudeCodeSkills = _disableClaudeCode || truthy("LIBRECODE_DISABLE_CLAUDE_CODE_SKILLS")
const _copyOnSelectEnv = process.env.LIBRECODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT

export const Flag = {
  LIBRECODE_GIT_BASH_PATH: process.env.LIBRECODE_GIT_BASH_PATH,
  LIBRECODE_CONFIG: process.env.LIBRECODE_CONFIG,
  LIBRECODE_CONFIG_CONTENT: process.env.LIBRECODE_CONFIG_CONTENT,
  LIBRECODE_DISABLE_AUTOUPDATE: truthy("LIBRECODE_DISABLE_AUTOUPDATE"),
  LIBRECODE_DISABLE_PRUNE: truthy("LIBRECODE_DISABLE_PRUNE"),
  LIBRECODE_DISABLE_TERMINAL_TITLE: truthy("LIBRECODE_DISABLE_TERMINAL_TITLE"),
  LIBRECODE_PERMISSION: process.env.LIBRECODE_PERMISSION,
  LIBRECODE_DISABLE_DEFAULT_PLUGINS: truthy("LIBRECODE_DISABLE_DEFAULT_PLUGINS"),
  LIBRECODE_DISABLE_LSP_DOWNLOAD: truthy("LIBRECODE_DISABLE_LSP_DOWNLOAD"),
  LIBRECODE_ENABLE_EXPERIMENTAL_MODELS: truthy("LIBRECODE_ENABLE_EXPERIMENTAL_MODELS"),
  LIBRECODE_DISABLE_AUTOCOMPACT: truthy("LIBRECODE_DISABLE_AUTOCOMPACT"),
  LIBRECODE_DISABLE_MODELS_FETCH: truthy("LIBRECODE_DISABLE_MODELS_FETCH"),
  LIBRECODE_DISABLE_CLAUDE_CODE: _disableClaudeCode,
  LIBRECODE_DISABLE_CLAUDE_CODE_PROMPT: _disableClaudeCode || truthy("LIBRECODE_DISABLE_CLAUDE_CODE_PROMPT"),
  LIBRECODE_DISABLE_CLAUDE_CODE_SKILLS: _disableClaudeCodeSkills,
  LIBRECODE_DISABLE_EXTERNAL_SKILLS: _disableClaudeCodeSkills || truthy("LIBRECODE_DISABLE_EXTERNAL_SKILLS"),
  LIBRECODE_FAKE_VCS: process.env.LIBRECODE_FAKE_VCS,
  LIBRECODE_SERVER_PASSWORD: process.env.LIBRECODE_SERVER_PASSWORD,
  LIBRECODE_SERVER_USERNAME: process.env.LIBRECODE_SERVER_USERNAME,
  LIBRECODE_ENABLE_QUESTION_TOOL: truthy("LIBRECODE_ENABLE_QUESTION_TOOL"),
  // A05 — LIBRECODE_DEV=1 exposes stack traces in HTTP error responses. Off
  // by default so production builds don't leak internal paths/line numbers.
  LIBRECODE_DEV: truthy("LIBRECODE_DEV"),

  // Experimental
  LIBRECODE_EXPERIMENTAL: _experimental,
  LIBRECODE_EXPERIMENTAL_FILEWATCHER: truthy("LIBRECODE_EXPERIMENTAL_FILEWATCHER"),
  LIBRECODE_EXPERIMENTAL_DISABLE_FILEWATCHER: truthy("LIBRECODE_EXPERIMENTAL_DISABLE_FILEWATCHER"),
  LIBRECODE_EXPERIMENTAL_ICON_DISCOVERY: _experimental || truthy("LIBRECODE_EXPERIMENTAL_ICON_DISCOVERY"),
  LIBRECODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    _copyOnSelectEnv === undefined
      ? process.platform === "win32"
      : truthy("LIBRECODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  LIBRECODE_ENABLE_EXA: truthy("LIBRECODE_ENABLE_EXA") || _experimental || truthy("LIBRECODE_EXPERIMENTAL_EXA"),
  LIBRECODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("LIBRECODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
  LIBRECODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("LIBRECODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
  LIBRECODE_EXPERIMENTAL_OXFMT: _experimental || truthy("LIBRECODE_EXPERIMENTAL_OXFMT"),
  LIBRECODE_EXPERIMENTAL_LSP_TY: truthy("LIBRECODE_EXPERIMENTAL_LSP_TY"),
  LIBRECODE_EXPERIMENTAL_LSP_TOOL: _experimental || truthy("LIBRECODE_EXPERIMENTAL_LSP_TOOL"),
  LIBRECODE_DISABLE_FILETIME_CHECK: truthy("LIBRECODE_DISABLE_FILETIME_CHECK"),
  LIBRECODE_EXPERIMENTAL_PLAN_MODE: _experimental || truthy("LIBRECODE_EXPERIMENTAL_PLAN_MODE"),
  LIBRECODE_EXPERIMENTAL_WORKSPACES: _experimental || truthy("LIBRECODE_EXPERIMENTAL_WORKSPACES"),
  LIBRECODE_EXPERIMENTAL_MARKDOWN: !falsy("LIBRECODE_EXPERIMENTAL_MARKDOWN"),
  LIBRECODE_MODELS_URL: process.env.LIBRECODE_MODELS_URL,
  LIBRECODE_MODELS_PATH: process.env.LIBRECODE_MODELS_PATH,
  LIBRECODE_DISABLE_CHANNEL_DB: truthy("LIBRECODE_DISABLE_CHANNEL_DB"),
  LIBRECODE_SKIP_MIGRATIONS: truthy("LIBRECODE_SKIP_MIGRATIONS"),
  LIBRECODE_STRICT_CONFIG_DEPS: truthy("LIBRECODE_STRICT_CONFIG_DEPS"),

  // Dynamic getters — evaluated at access time, not module load time,
  // so that tests and external tooling can set these env vars at runtime
  get LIBRECODE_DISABLE_PROJECT_CONFIG() {
    return truthy("LIBRECODE_DISABLE_PROJECT_CONFIG")
  },
  get LIBRECODE_TUI_CONFIG(): string | undefined {
    return process.env.LIBRECODE_TUI_CONFIG
  },
  get LIBRECODE_CONFIG_DIR(): string | undefined {
    return process.env.LIBRECODE_CONFIG_DIR
  },
  get LIBRECODE_CLIENT(): string {
    return process.env.LIBRECODE_CLIENT ?? "cli"
  },
}
